# -*- coding: utf-8 -*-
"""hex2binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOI4DZb5De-q1QbndPmMSyU9eo7BjfVo
"""

import pandas as pd

# Load the hexadecimal dataset
hex_file = "/content/hexadecimal_spoofing-GAS.csv"  # Update with your file name
hex_df = pd.read_csv(hex_file)

# Specify the hexadecimal columns to be converted
hex_columns = ['DATA_0', 'DATA_1', 'DATA_2', 'DATA_3', 'DATA_4', 'DATA_5', 'DATA_6', 'DATA_7']

# Convert hexadecimal columns to binary
for col in hex_columns:
    # Convert each value in the column from hexadecimal to binary and pad to 8 bits
    hex_df[f"{col}_binary"] = hex_df[col].apply(lambda x: bin(int(str(x), 16))[2:].zfill(8) if not pd.isnull(x) and isinstance(x, (str, int, float)) else None)

    # Split the binary strings into individual bits and store them in separate columns
    for i in range(8):
        hex_df[f"{col}_bit_{i}"] = hex_df[f"{col}_binary"].apply(lambda x: x[i] if x else None)

# Drop intermediate binary columns if not needed
hex_df.drop(columns=[f"{col}_binary" for col in hex_columns], inplace=True)

# Move 'label', 'category', and 'specific_class' columns to the end
columns = hex_df.columns.tolist()
special_columns = ['label', 'category', 'specific_class']
reordered_columns = [col for col in columns if col not in special_columns] + special_columns
hex_df = hex_df[reordered_columns]

# Save the resulting binary dataset to a new CSV file
output_file = "converted_binary_dataset.csv"
hex_df.to_csv(output_file, index=False)

print(f"Binary dataset saved to {output_file}")